<?php

$otpExpiration = config('auth.mobile_otp.expire');

$relocationCompletionOtpExpiration = config('happylocate.pam.relocation.completion_otp_expiry', 30);

return [

    /*
    |--------------------------------------------------------------------------
    | SMS Templates
    |--------------------------------------------------------------------------
    |
    | The following language lines are used as SMS templates with replacer for
    | appropriate fields that needs to be dynamically set.
    |
    */

    'generic-otp' => 'Your QuikService OTP is :otp. Do not share this with anyone. Valid for ' . $otpExpiration . ' minutes.',
    'login-otp' => 'Your QuikService OTP is :otp. Do not share this with anyone. Valid for ' . $otpExpiration . ' minutes.',
    'password-reset-otp' => 'Your QuikService password reset OTP is :otp. Do not share this with anyone. Valid for ' . $otpExpiration . ' minutes.',
    'pam-premove-confirmed-user' => 'Your Premove Survey is scheduled with :vendor on :appointmentDate at :confirmedTimeSlot',
    'pam-premove-confirmed-vendor' => 'Your Premove Survey is confirmed with :user, :mobile on :appointmentDate at :confirmedTimeSlot',
    'pam-quotation-generated-user' => 'Quotation shared by :vendor is :quotationAmount for your move from :fromCity to :toCity.',
    'pam-quotation-accepted-admin' => 'Quote :quotationId of INR :amount generated by :vendor is accepted by :user for movement on :relocationDate Check PYMT',
    'pam-payment-done-user' => 'INR :amount/- Received for your movement on :relocationDate by :vendor',
    'pam-user-made-payment-vendor' => 'Congratulation! Your Quote is Approved and INR :amount received from :user. Please initiate the movement',
    'pam-user-made-payment-admin' => 'Payment of INR :amount received from :user for move on :relocationDate by :vendor :quotationId',
    'relocation-completion-otp' => 'Dear :user, Share this OTP :otp with Vendor to confirm successful Delivery of your Household Goods. Valid for ' . $relocationCompletionOtpExpiration . ' minutes.',

    /**
     * Corporate relocation request templates.
     */
    'corporate-pam-request-approved' => "Dear :employeeName, Your Relocation Request [RR ID :pamRequestId] is accepted. You can now go ahead with the Payment for relocation.",
    'corporate-pam-request-declined' => "Dear :employeeName, Your Relocation Request (RR ID :pamRequestId) is declined by :declinedApprover.",


    // Hotel Booking

    'hotel-booking-confirmed' => 'Your Hotel Booking confirmed for :hotel. Booking ID :booking_id.',
    'hotel-booking-pending' => 'Your hotel booking is not confirmed for :hotel. Booking ID :booking_id. We will notify once confirmed.',
    'hotel-booking-cancel-confirmed' => 'Your hotel booking cancellation for :hotel is confirmed. Booking ID :booking_id',
    'hotel-booking-cancel-pending' => 'Your hotel booking cancellation is pending. Booking ID :booking_id. We will notify once confirmed.',

    // Hotel Reservation

    'hotel-reservation-confirmed' => 'Your Hotel reservation is Confirmed for :hotel. Reservation ID :reservation_id Checkin - :checkin',
    'hotel-reservation-cancelled' => 'Your Hotel reservation is Cancelled for :hotel. Reservation ID :reservation_id Checkin - :checkin',
    'hotel-reservation-declined' => "Your Hotel reservation is not Confirmed for :hotel due to: :reason. You can check out similar hotels.",

    // Travel Request

    'travel-request-approved' => "Your Business Travel Request [BTR ID :travel_request_id ] is accepted. You can now go ahead with Reservation.",
    'travel-request-declined' => "Your Business Travel Request [BTR ID :travel_request_id ] is declined by :approver_name.",

];
